// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package com.nashoba.robotics;

import com.nashoba.robotics.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI 
{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS


	    
        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());

        SmartDashboard.putData("Drive Drive Command", new DriveDriveCommand());

        SmartDashboard.putData("Drive Brake Command", new DriveBrakeCommand());

        SmartDashboard.putData("Shooter Idle Command", new ShooterIdleCommand());

        SmartDashboard.putData("Shooter Load Command", new ShooterLoadCommand());

        SmartDashboard.putData("Shooter Stop Command", new ShooterStopCommand());

        SmartDashboard.putData("Track Idle Command", new TrackIdleCommand());

        SmartDashboard.putData("Track Drive Down Until Force Command", new TrackDriveDownUntilForceCommand());

        SmartDashboard.putData("Compressor Start Command", new CompressorStartCommand());

        SmartDashboard.putData("Compressor Stop Command", new CompressorStopCommand());

        SmartDashboard.putData("Tipping Deploy Command", new TippingDeployCommand());

        SmartDashboard.putData("Tipping Undeploy Command", new TippingUndeployCommand());

        SmartDashboard.putData("Tipping Idle Command", new TippingIdleCommand());

        SmartDashboard.putData("Cancel All Command", new CancelAllCommand());

        SmartDashboard.putData("Shoot Four Times Command", new ShootFourTimesCommand());

        SmartDashboard.putData("Compressor Automatic Toggle Command", new CompressorAutomaticToggleCommand());

        SmartDashboard.putData("Track Deploy Brake Command", new TrackDeployBrakeCommand());

        SmartDashboard.putData("Track Undeploy Brake Command", new TrackUndeployBrakeCommand());

        SmartDashboard.putData("Shooter Run Command", new ShooterRunCommand());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

